export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIE_START: 'category/FETCH_CATEGORIE_START',
    FETCH_CATEGORIE_SUCCESS: 'category/FETCH_CATEGORIE_SUCCESS',
    FETCH_CATEGORIE_FAILED: 'category/FETCH_CATEGORIE_FAILED',
}